console.log("Hola Mundo")
console.log("Mi nombre es:")
console.log("Juan Caballero")
console.log("Tengo:")
console.log("17 años")
console.log("Vivo en:")
console.log("Barranquilla, Colombia")
console.log("Estudio en:")
console.log("El SENA")